services:
  pip-compile:
    entrypoint:
      - /home/python/venv/bin/pip-compile
    image: ghcr.io/williamjacksn/pip-tools:py3.12
    init: true
    volumes:
      - ./:/home/python/file-tools
    working_dir: /home/python/file-tools

  shell:
    image: ghcr.io/williamjacksn/file-tools
    init: true
    volumes:
      - ./:/home/python/file-tools
